main.tf
modules/logs/main.tf
modules/logs/outputs.tf
modules/logs/variables.tf
outputs.tf
variables.tf

Added (sub) module to create Kinesis Firehose Delivery streams for an application to stream app logs to an (existing) AWS elasticsearch domain using Firelens/Fluend-Bit.
Todo:
- example
- documentation
- default permission to put log events

added log streaming sub module

---

README.md
docs/part2.md
examples/public-service/main.tf
main.tf
modules/ecr/main.tf
modules/ecr/outputs.tf
modules/ecr/variables.tf
outputs.tf
variables.tf

ecr resource is now a configurable sub-module
tags and name are not configurable to enforce our best practices
this also provides options to configure image scanning like proposed in #3
but without enabling it by default since this doesn't reflect the
terraform defaults.

extracted ecr as submodule

---

README.md
alb.tf
docs/part1.md
docs/part2.md
examples/public-service/main.tf
main.tf
outputs.tf
route53.tf
variables.tf

In order to support services which don't need to be attached to an ALB target group (e.g. services in an App Mesh using grpc), the following adjustments have been made:
- `health_check` is now an optional map to capture configuration supported for a [aws_lb_target_group ](https://www.terraform.io/docs/providers/aws/r/lb_target_group.html#health_check)
- `alb_listener_priority` is now optional
- new variable `alb_attach_public_target_group` to attach the service to the public ALB and create a Route53 record (defaults to `true`)
- new variable `alb_attach_private_target_group` to attach the service to the private ALB and create a Route53 record (defaults to `true`)
This needs to be released as a `MINOR` version (`health_check` needs to be adjusted in clients)

optional ALB configuration

---

README.md
alb.tf
docs/part1.md
docs/part2.md
variables.tf

User can activate COGNITO authentication by passing:
```
module "service" {
alb_cogino_pool_arn           = data.terraform_remote_state.cognito.outputs.alb_cogino_pool_arn
alb_cogino_pool_client_id     = data.terraform_remote_state.cognito.outputs.alb_cogino_pool_client_id
alb_cogino_pool_domain        = data.terraform_remote_state.cognito.outputs.alb_cogino_pool_domain
}
```

Auth for the public ALB's HTTPS listener

---

modules/deployment/code_build.tf

Before this PR CodeBuild created CloudWatch log groups automatically (without a retention time and tags). As a consequence those log groups remained after a `terraform destroy`.
With this PR we manage those log groups with terraform. To apply this to existing services, please delete automatically create log groups manually before `terraform apply`.

manage cloudwatch logs for code build

---

README.md
docs/part1.md
docs/part2.md
main.tf
modules/logs/main.tf
modules/logs/outputs.tf
modules/logs/variables.tf
outputs.tf
variables.tf

with Fluent-Bit 1.5 we can now send logs directly to Elasticsearch - support for Kinesis Firehose is dropped. See [fluent-bit](https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch) documentation for configuration details  and options.
**This should be released as a new minor version and applied to all clients**
fixes #28

send logs directly to Elasticsearch

---

modules/deployment/data.tf
modules/deployment/iam_code_pipeline.tf
versions.tf

```
module.service.module.code_deploy.aws_iam_role_policy_attachment.trigger[0]: Refreshing state... [id=xxx]
aremoved datasource because it fails when bootstrapping new services and replaced it with manual ARN build
Error: ECR Repository (xxx) not found
```

removed datasource because it fails when bootstrapping new services and replaced it with manual ARN build

---

README.md
docs/part1.md
docs/part2.md
examples/public-service/main.tf
main.tf
modules/logs/main.tf
modules/logs/outputs.tf
modules/logs/variables.tf
outputs.tf
variables.tf

central CloudWatch log group for a service
* all sitecars can store container logs in one log group using prefixes
* IAM permissions centralized in module instead of clients
`logs_fluentbit_cloudwatch_log_group_name`

central CloudWatch log group for a service

---

alb.tf
main.tf
modules/deployment/code_build.tf
modules/deployment/code_pipeline.tf
modules/deployment/iam_code_pipeline.tf
modules/deployment/variables.tf
variables.tf

*simplified deployment*
- no tags other than the trigger tag are required (`tag:production`)
- task def will use the full image-uri (`...@sha256:...`)
- bumped to latest code build image (v3)
also fixed typo `cognito`
closes #16

Deployment 2.0

---

.github/workflows/workflow.yaml
.pre-commit-config.yaml
Makefile
README.md
docs/part2.md
main.tf
modules/ecr/main.tf
variables.tf

Enable default ECR lifecycle policy (which can be disabled). In addition, disabled default policy if custom JSON is specified, see https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_lifecycle_policy
```
╷
│ Error: Null condition
│ 
│   on .terraform/modules/service/modules/ecr/main.tf line 19, in resource "aws_ecr_lifecycle_policy" "default_lifecycle_policy":
│   19:   count      = var.enable_default_lifecycle_policy ? 1 : 0
│     ├────────────────
│     │ var.enable_default_lifecycle_policy is null
│ 
│ The condition value is null. Conditions must either be true or false.
```
and:
> Only one aws_ecr_lifecycle_policy resource can be used with the same ECR repository. To apply multiple rules, they must be combined in the policy JSON.

fix: apply default ECR lifecycle policy if clients do not specify override

---

.github/workflows/workflow.yaml
README.md
docs/part2.md
main.tf
variables.tf
versions.tf

- Adds tf support for optional object values with defaults.
- Adds support for capacity providers for FARGATE and FARGATE_SPOT.
- Adds support for deployment circuit breakers.
- This change dropps support for many terraform versions 🚧🔥

Add support for capacity providers by using tf 1.3 optional object parmeters

---

main.tf

this prevents errors for new service creations using autoscaling

fix: added dependency to ecs service for autoscaling target resource

---

.pre-commit-config.yaml
README.md
container_definition.tf
envoy.tf
outputs.tf

- default to enabled `Aws_Auth` and enabled `Suppress_Type_Name` in Opensearch log configurations
- created distinct outputs for task role and task execution role
- default to secure communication with Opensearch domains using fine-grained access controll and/or access policies
- default to Opensearch domains without deprecated mapping type (see [Fluentbit docs](https://docs.fluentbit.io/manual/pipeline/outputs/opensearch))

refactor(fluentbit): default to enabled Aws_Auth

---

container_definition.tf

This brings the code into alignment with other uses of the `ecr_reposiory_name` variable

fix: consistent handling of var.ecr_repository_name

---

otel.tf

> You are receiving this message because you are using the AWS Distro for OpenTelemetry (ADOT) collector to send metrics to Amazon Managed Service for Prometheus.
> In order to remain fully compatible with the upstream OpenTelemetry collector, starting with version v0.35.0 [1] of the ADOT collector there are changes in the naming of metrics exported by the Prometheus remote write exporter. Suffixes may be added to metrics so that they follow the best practices for naming metrics [2]. If you don’t take any action this might result in existing dashboards or alarms referencing stale metrics.
> We ask you to please review our guide [3] to understand the changes being made and to determine what the behaviour is that you want to use for this component (add suffixes or don't add suffixes).

chore(otel): update collector version

---

envoy.tf
fluentbit.tf
variables.tf

https://docs.fluentbit.io/manual/administration/monitoring

feat(envoy): add dependsOn on logging side car if present

---

fluentbit.tf
otel.tf

bugfix: get awslogs-group either from `aws_cloudwatch_log_group.containers` or use provided `var.cloudwatch_logs.name`
tries to fix: https://github.com/stroeer/paper/actions/runs/10056993152/job/27797245512#step:5:105

fix: support awslogs-group from provided name

---

README.md
examples/complete/README.md
examples/complete/data.tf
examples/complete/main.tf
examples/complete/outputs.tf
examples/complete/versions.tf
examples/fixtures/context/Dockerfile
main.tf
modules/deployment/iam_code_pipeline.tf
outputs.tf

- Enhances complete example so it can be applied without errors
- fixes security group code, so new services can be create with `create_ingress_security_group = true`, see https://github.com/stroeer/terraform-aws-ecs-fargate/issues/149
> [!CAUTION]  
> When applying this code, the existing ingress security group will be replaced, make sure this is acceptable in your environment

fix(alb): complete example can be applied without errors

---

container_definition.tf
envoy.tf
variables.tf

Allow changing the `aws_region` used by firelense to sign off requests in case the stack was deployed in a region that does match OpenSearch's region.

feat(multi-region): configurable aws_region for firelense

---

Makefile

use `gh` cli tooling for creating local releases
- simplify release process
- use auth from our standard tooling

chore(gh): use GitHub cli for creating releases

---

.github/workflows/pr-title.yaml
variables.tf

Currently, you can use "null" for the value of the codebuild-variables. If you do that, you will receive an error from the underlying module.
In order to fix this, I've set the variables to `nullable=false` which should protect you from this error.
If you paste null, then the default value will be used (source: https://developer.hashicorp.com/terraform/language/values/variables#disallowing-null-input-values)

feat: forbid nullable codebuild variables, to use default variables on null

---

otel.tf

Summarized breaking changes since 0.36.0 https://github.com/aws-observability/aws-otel-collector/releases
- The memory_ballast extension was removed upstream and ADOT Collector in favor of the GOMEMLIMIT environment variable, See the [Go documentation](https://pkg.go.dev/runtime#hdr-Environment_Variables) for more information about GOMEMLIMIT's usage.
- The logging exporter has been removed upstream in favor of the debug exporter. This release removes the logging exporter. See https://github.com/open-telemetry/opentelemetry-collector/issues/11337 to migrate to the debug exporter.
- Note: Expansion of BASH-style environment variables, such as $FOO, is no longer be supported. Use ${FOO} or ${env:FOO} instead.

chore: dep update otel to 0.42

---

.github/workflows/pr-title.yaml
.github/workflows/static-analysis.yaml

This pull request includes updates to the GitHub Actions workflows to use specific versions of actions for better stability and security.
Updates to GitHub Actions workflows:
* [`.github/workflows/pr-title.yaml`](diffhunk://#diff-872a5dc5cb41e92ee26fda3012879c7f6b8dcdedd57822c134fbf887886ca4eeL15-R15): Updated the `amannn/action-semantic-pull-request` action to use a specific commit hash `0723387faaf9b38adef4775cd42cfd5155ed6017` corresponding to version 5.5.3.
* [`.github/workflows/static-analysis.yaml`](diffhunk://#diff-5d68f6ca696b457d708e1895ce1dcab8820f9d6d9357b3876176cbcdd9808b98L30-R30): Updated the `terraform-linters/setup-tflint` action to use a specific commit hash `90f302c255ef959cbfb4bd10581afecdb7ece3e6` corresponding to version 4.1.1.
* …

chore(gh): pinned versions of unverified GitHub actions

---

.pre-commit-config.yaml
.tflint.hcl
envoy.tf

This pull request includes updates to dependencies and configurations for Terraform and TFLint, as well as an update to the Envoy container image version in the `envoy.tf` file. These changes ensure compatibility with newer versions and improve functionality.
* [`envoy.tf`](diffhunk://#diff-ded462a2e0a4c98d25a7d3ed8e7f7206713df6c525ecaa2785b8d9b0cabefb94L6-R6): Updated the Envoy container image version from `v1.27.3.0-prod` to `v1.29.12.1-prod` to use the latest version.
* [`.pre-commit-config.yaml`](diffhunk://#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9L3-R3): Updated `pre-commit-terraform` hook version from `v1.99.0` to `v1.99.1`.
* [`.tflint.hcl`](diffhunk://#diff-c82c2fd3fe5d1315facdf6794e11d51e0bf10783e6ef34a270996a62bccf605dL7-R7): Updated the `aws` plugin …

chore(envoy): bumped default envoy to v1.29.12.1-prod

---

main.tf

```
Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/prod.service/main.tf line 68, in resource "aws_security_group_rule" "trusted_egress_attachment":
│   68:   for_each                 = { for route in local.ingress_targets : "${route["prefix"]}-${route["protocol"]}-${route["from_port"]}-${route["to_port"]}" => route }
│     ├────────────────
│     │ local.ingress_targets has a sensitive value
│ 
│ Sensitive values, or values derived from sensitive values, cannot be used as for_each arguments. If used, the sensitive value could be exposed as a resource instance key.
╵
```

fix: local ingress targets are nonsensitive

---

README.md
examples/complete/README.md
examples/complete/main.tf
iam.tf

This PR refactors IAM policy creation to resolve Terraform planning issues for new stacks by consolidating separate SSM and logs policies into a single policy that can be evaluated at plan time. The changes enable dynamic SSM permissions for both main container definitions and additional container definitions while maintaining proper IAM access controls.
- Consolidates separate IAM policies (SSM, logs, execute command) into unified policies to avoid count dependencies on unknown resources
- Enhances the complete example to demonstrate SSM parameter store integration with secrets
- Updates documentation to reflect the new IAM resource structure
terraform plan for new stacks currently fails with
```
Error: Invalid count argument
│ 
│   on ../../iam.tf line 38, in resource …
```

fix(iam): dynamic SSM permissions for new services
